{% set name = "hloc" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cvg/Hierarchical-Localization/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0c0e17cdddecf386aa58d50abed76ba6d9f46c59af205df445b2fe6d632753cb

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytorch
    - torchvision
    - numpy
    - opencv
    - tqdm
    - matplotlib-base
    - plotly
    - scipy
    - h5py
    - pycolmap
    - kornia
    - gdown

test:
  imports:
    - hloc

about:
  home: https://github.com/cvg/Hierarchical-Localization
  license: Apache-2.0
  license_file: LICENSE
  summary: 'This is hloc, a modular toolbox for state-of-the-art 6-DoF visual localization.'
  description: 'It implements Hierarchical Localization, leveraging image retrieval and feature matching, and is fast, accurate, and scalable.'
  doc_url: https://github.com/cvg/Hierarchical-Localization
  dev_url: https://github.com/cvg/Hierarchical-Localization

extra:
  recipe-maintainers:
    - Tobias-Fischer
